<script setup>
    //General Imports
    import {ref} from "vue";
    import { useVueToPrint } from "vue-to-print";

    //Component Imports
    //...

    //Props
    import Nesting from "@/Components/Nesting/Nesting.vue";
    import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
    import VisualNestingOffcuts from "@/Components/VisualNestingOffcuts.vue";
    import ListPurchasables from "@/Components/ListPurchasables.vue";
    import VisualNestingWithBars from "@/Components/VisualNestingWithBars.vue";
    import VisualBundleNest from "@/Components/VisualBundleNest.vue";
    import VisualOrderList from "@/Components/VisualOrderList.vue";
    import DisplayPiecesList from "@/Components/DisplayPiecesList.vue";


    const props = defineProps({
        pieces: Object,
        projectsReadyForBatching: Object,
        piecesGroupedBySupplierGroup: Object,
        usage: Object,
        type: String,
        width: Number,
        lettersProjectArray: Object,
        redirect: String,
        batch: Object,
    });

    //Form
    //...

    //Shared data
    //...

    //Variables
    const currentSupplierGroup = ref(Object.keys(props.piecesGroupedBySupplierGroup.assigned)[0]);
    const printPreview = ref(true);

    //Shared Methods
    //...

    //Methods
    const componentRef = ref();
    const { handlePrint } = useVueToPrint({
        content: componentRef,
        documentTitle: "AwesomeFileName",
    });


</script>

<template>
    <AuthenticatedLayout>
        <div class="h-10"></div>
        <div class="text-center p-3">
            <button
                @click="handlePrint"
                class="bg-green-50 px-3 py-2 rounded border-2 border-green-200"
            >
                Print <i class="fa-solid fa-print"></i>
            </button>
            <p class="text-xs text-gray-700">
                Set printer to A4
            </p>
        </div>

<!--        <p @click="printPreview = !printPreview">Toggle display</p>-->
        <div
            ref="componentRef"
            style="width: 21cm;"
            class="mx-auto"
        >
            <div
                :class="printPreview ? 'pagePrint' : 'pageDisplay'"
                size="A4"
            >
                <!-- Header -->
                <div class="grid grid-cols-3 p-4">
                    <div class="font-bold"></div>
                    <div class="flex gap-x-3 justify-center">
                        <div>
                            Batch: {{batch.id}}
                        </div>
                        <div>
                            p[x]/[x]
                        </div>
                    </div>
                    <div class="text-right">
                        SteelNesting.com.au
                    </div>
                </div>

                <!-- Nesting summary -->
                <div class="text-center mt-3">
                    <h1 class="text-2xl font-bold">Nesting Summary</h1>
                </div>


                <!-- batch created by -->
                <div class="col-span-2 mt-5">
                    <h2><b>Batch generated by:</b> {{batch.user.name}} ({{batch.user.email}})</h2>

                </div>

                <!-- included projects -->
                <div class="col-span-2 mt-5">
                    <h2 class="font-bold">Included Projects:</h2>
                    <ul>
                        <li v-for="(project,index) in projectsReadyForBatching.data">
                            - Project '<b>{{lettersProjectArray[project.id]}}</b>': <i>{{project.name}}</i> ({{project.projectManager.name}}'s project)
                        </li>
                    </ul>
                </div>
                <!-- Usage stats-->
                <div class="col-span-3 mt-5 text-left">
                    <table class="w-full">
                        <tr>
                            <th>Total Material</th>
                            <th>Total Used Material</th>
                            <th>Total Reusable</th>
                            <th>Total Scrap</th>
                            <th>Efficiency</th>
                        </tr>
                        <tr>
                            <td>{{ (usage.METERAGE.totalPurchasedMaterial/1000).toLocaleString() }}m</td>
                            <td>{{ (usage.METERAGE.totalUsedMaterial/1000).toLocaleString() }}m</td>
                            <td>{{ (usage.METERAGE.totalReusable/1000).toLocaleString() }}m</td>
                            <td>{{ (usage.METERAGE.totalScrap/1000).toLocaleString() }}m</td>
                            <td>{{ usage.METERAGE.efficiency }}%</td>
                        </tr>
                    </table>
                </div>
            </div>

            <template v-for="(batchGroup,batchLabel) in piecesGroupedBySupplierGroup.assigned">

                <div class="grid grid-cols-1">
                    <div v-for="item in batchGroup">

                        <div
                            :class="printPreview ? 'pagePrint' : 'pageDisplay'"
                            size="A4"
                        >
                            <!-- Header -->
                            <div class="grid grid-cols-3 p-4">
                                <div class="font-bold">
                                    {{item.product_derived_label}}
                                </div>
                                <div class="flex gap-x-3 justify-center">
                                    <div>
                                        Batch: {{batch.id}}
                                    </div>
                                    <div>
                                        p[x]/[x]
                                    </div>
                                </div>
                                <div class="text-right">
                                    SteelNesting.com.au
                                </div>
                            </div>

                            <div class="grid grid-cols-4 p-5 gap-3">
                                <!-- Spec -->
                                <div>
                                    <h2 class="font-bold">Material Spec</h2>
                                    {{item.product_derived_label}}
                                    <p class="text-xs">
                                        <span class="block">Product: {{item.product_category}}</span>
                                        <span class="block">Material: {{item.material}}</span>
                                        <span class="block">Grade: {{item.grade}}</span>
                                        <span class="block">Surface: {{item.surface}}</span>
                                    </p>
                                </div>
                                <!-- Pieces -->
                                <div>
                                    <h2 class="font-bold">Pieces</h2>
                                    <DisplayPiecesList
                                        :nestingAlgo="item.algo"
                                        :measurementUnit="item.nominal_units"
                                        :pieces="item.pieces"
                                        :lettersProjectArray="lettersProjectArray"
                                    />
                                </div>
                   
                                <!-- order list -->
                                <div>
                                    <h2 class="font-bold">Order List</h2>
                                    <template v-for="bar in item.nested.orderList">
                                        <VisualOrderList
                                            :stockLength="bar.result"
                                            :pieces="bar.result.pieces"
                                            :measurementUnit="item.nominal_units"
                                            :waste="bar.result.waste"
                                            :qty="bar.count"
                                        />
                                    </template>
                                </div>
                                <!-- Nesting -->
                                <div class="col-span-4">

                                    <!-- Nesting algorithm: meterage -->
                                    <div v-if="item.algo === 'METERAGE'">

                                        <!-- offcuts -->
                                        <div v-if="Object.values(item.nested.bestResultOffcuts.utilisedOffcutBars).length > 0">
                                            <h2 class="font-bold text-xl">Offcut usage</h2>
                                            <VisualNestingOffcuts
                                                :utilisedOffcutBars="item.nested.bestResultOffcuts.utilisedOffcutBars"
                                                :measurementUnit="item.nominal_units"
                                            />
                                        </div>

                                        <template v-if="Object.values(item.nested.utilisedBars).length > 0">
                                            <h2 class="font-bold text-xl mt-5">New stock usage</h2>
                                            <!-- new stock nesting -->
                                            <VisualNestingWithBars
                                                :utilisedBars="item.nested.utilisedBars"
                                                :measurementUnit="item.nominal_units"
                                            />
                                            <p
                                                v-if="item.nested.tooLong.length > 0"
                                                class="text-red-500 font-bold mt-2"
                                            >
                                                Pieces too long: <span v-for="unfit in item.nested.tooLong">{{ parseFloat(unfit.length).toLocaleString()}} mm ({{unfit.letter}}), </span>
                                            </p>
                                        </template>
                                    </div>
                                    <!-- Nesting algorithm: bundle -->
                                    <div v-if="item.algo === 'BUNDLE'">
                                        <VisualBundleNest
                                            :nestData="item.nested"
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>



                    </div>
                </div>
            </template>
        </div>

<!--        <Nesting-->
<!--            :width="width"-->
<!--            :projectsReadyForBatching="projectsReadyForBatching"-->
<!--            :lettersProjectArray="lettersProjectArray"-->
<!--            :usage="usage"-->
<!--            :piecesGroupedBySupplierGroup="piecesGroupedBySupplierGroup"-->
<!--            :currentSupplierGroup="currentSupplierGroup"-->
<!--            :redirect="redirect"-->
<!--            :batch="batch"-->
<!--        />-->
    </AuthenticatedLayout>
</template>

<style scoped>
    .pageDisplay {
        background: white;
        display: block;
        margin: 0 auto;
        margin-bottom: 0.5cm;
        box-shadow: 0 0 0.5cm rgba(0,0,0,0.5);
        width: 21cm;
        height: 29.7cm;
        padding: 15px;
    }
    .pagePrint {
        background: white;
        display: block;
        margin: 0;
        margin-bottom: 0;
        box-shadow: 0 0 0.5cm rgba(0,0,0,0.5);
        width: 21cm;
        height: 29.7cm;
        padding: 15px;
    }
</style>
